### ISSUE TITLE
Loading WAVEEDIT Wavetable into Limonade

### ISSUE THREAD

**Issue by therealkitman** [sebastien-bouffier/Bidoo#117]
Linux opensuse Leap 15.0
Version V1.0.3
Hi.
I read issue #93 regarding loading wavetables into Limonade. I still have trouble.

I created a simple wavetable in [WAVEEDIT](http://synthtech.com/waveedit) of 4 simple shapes with the remaining 60 waves flat. 
[4shapes.zip](https://github.com/sebastien-bouffier/Bidoo/files/3438750/4shapes.zip)

![image](https://user-images.githubusercontent.com/14888092/62000896-6ea13900-b115-11e9-830d-c680e0c4f546.png)
I then wanted to load this table into Limonade using the double ~ function and nothing happens except the CPU% red line jumping to ~150% before falling back to normal.
I can load this same wavetable into Nysthi's SEVEN SEAS wavetable oscillator as well as into Canard and Ouaive.
![image](https://user-images.githubusercontent.com/14888092/62000911-e7a09080-b115-11e9-9729-e7e7f25515d7.png)
I can load the individual waves separately using the single ~ function. Am I doing something wrong?
I'm still a novice with wavetables  :smile: 
Thanks,
Chris.

**Comment by sebastien-bouffier** [comment]
Hi @therealkitman  v1.0.3 has a bug on wavetable loading, it is fixed in 1.0.4. Unfortunately this version seems to lead to another issue ... module explorer crashes Rack. I hope I will achieve to find why and soon you will be able to play with limonade.
Best

**Comment by therealkitman** [comment]
No worries Sebastien. I'll wait for your announcement for 1.0.4.
Thanks.

**Comment by therealkitman** [comment]
HI. Just tested v1.0.4. Problem loading a wavetable still exists.
Regards.

**Comment by sebastien-bouffier** [comment]
Hi 1.0.5 should solve the wavetable loading issue.

**Comment by therealkitman** [comment]
Hi. I have v1.0.5 but it's not behaving as expected. I have loaded my 4shapes.wav wave table but Limonade is loading all 4 waves in the first frame but I expect 4 separate frames with each unique wave shape.

![image](https://user-images.githubusercontent.com/14888092/62910011-7fa6a700-bdb1-11e9-8e6d-1ca5e66d160d.png)

**Comment by sebastien-bouffier** [comment]
It looks like your sample is a half frame long, because a frame is 2048 samples by default. You can change this value to 256 in the edit box on top of function buttons and reload your sample.

**Comment by therealkitman** [comment]
AH HA! :smile: Now loading as expected though to be honest I do not fully understand samples vs frames.
![image](https://user-images.githubusercontent.com/14888092/62935879-db495280-bdfa-11e9-9305-b93cefb0997c.png)
However, when I go to Morph the wavetable I get some unexpected results.
![image](https://user-images.githubusercontent.com/14888092/62935961-15b2ef80-bdfb-11e9-92a7-5490b2df6079.png)
When I click Remove Morphing those weird extra waveforms persist.
![image](https://user-images.githubusercontent.com/14888092/62936016-3d09bc80-bdfb-11e9-8712-ae493e5d0611.png)
Is my 4 wave wavetable too simple?

**Comment by sebastien-bouffier** [comment]
Can you send me your sample please ?
Sorry I found it in your first post

**Comment by sebastien-bouffier** [comment]
There is a bug in morphing that adds frames between the ones you import. If I remove the 60 flat frames at the end of the wavetable then morphing works fine. I will fix it.

**Comment by sebastien-bouffier** [comment]
1.0.6 is released ans should fix your issue.
Best

**Comment by therealkitman** [comment]
Hi, all good. thank you very much!!!
