### ISSUE TITLE
Zou Mai PASTE function when nothing was been copied causes a crash 

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#149]
OS (if applicable): win
Version (or "dev" if compiling from source): 1.1.6
Hi Sebastian! So the topic speaks for itself. There is no reason to paste something when nothing was been copied before but if user do it occasionally...I don't think this is ok). Cheers!

**Comment by sebastien-bouffier** [comment]
Hi, fixed in 1.1.18 to be release
Cheers

**Comment by Petervos2018** [comment]
> 
> 
> Hi, fixed in 1.1.18 to be release
> Cheers

When ? I just got 1.1.16 just now 20-04-2020 20:45 via the PM ?

Looks like you missed the boat ?

https://github.com/VCVRack/library/issues/418#issuecomment-616736458

Greetings Peter

EDIT: new knobs look nice :)

**Comment by sebastien-bouffier** [comment]
Hi @Petervos2018  yep boat missed :)

**Comment by sebastien-bouffier** [comment]
Hi @vcvrackideas  I close this issue since it is fixed in 1.1.21 do not hesitate to reopen it if you consider the issue is not solved.
