### ISSUE TITLE
antN degraded performance

### ISSUE THREAD

**Issue by davephillips** [sebastien-bouffier/Bidoo#73]
Fedora 23 Linux
Rack master

Yesterday and this morning I've experienced serious persistent problems when running antN. Specifically, my system was affected to the point where my mouse pointer movement would become sluggish, response to clicks was very slow, and screen redraws were also slowed down significantly. Eventually I would have to kill Rack externally to get my system back under control. antN is the only module that caused this behavior.

The following output might suggest what is causing the degraded performance:

$ ldd plugin.so 
	linux-vdso.so.1 (0x00007fff702a8000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f273abf5000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f273a86d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f273a565000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f273a34d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2739f85000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f2739d5d000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007f2739b25000)
	libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f27398f5000)
	libssl3.so => /lib64/libssl3.so (0x00007f27396a5000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f273947d000)
	libnss3.so => /lib64/libnss3.so (0x00007f273914d000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f2738f1d000)
	libplds4.so => /lib64/libplds4.so (0x00007f2738d15000)
	libplc4.so => /lib64/libplc4.so (0x00007f2738b0d000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f27388cd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f27386ad000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f27384a5000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f2738255000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f2737f6d000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f2737d35000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f2737b2d000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f273791d000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f27376c5000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f27374ad000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558988567000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f2737235000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f2736dcd000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f2736bc5000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f27369b5000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f27367ad000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f273658d000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f273636d000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f2736145000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f2735f0d000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f2735c95000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f2735a8d000)

Are the dependencies for SSH, OpenSSL, selinux, and crypto really required ?

Here's the output for the Bidoo plugin.so dependencies for Rack 0.5.0:

$ ldd plugin.so 
	linux-vdso.so.1 (0x00007ffc30400000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1f6fbe5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1f6f8dd000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1f6f6c5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1f6f2fd000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563f27106000)

It seems to me that plugin.so has become "dependent-heavy" and is perhaps causing conflicts with Rack itself. I'm not a programmer, so I'm only guessing, but it is clear that former versions of the Bidoo modules were much more light-weight than the current version. I'm happy to see that you removed the GLFW dependency, perhaps the same can be done with some others to lighten the load ?

Btw, the issue doesn't appear to be a matter of CPU usage. The DSP usage meter on QJackCtl (the manager GUI I use to control JACK) shows a mere 4.x% usage when running the simple examples that are causing the degraded performance.

antN is one of my favorite modules for Rack, I hope the problem can be resolved easily. :)

**Comment by sebastien-bouffier** [comment]
hello ... openssl is required to perform https for curl. 0.6 version of my plugin should have the same dependencies as 0.5, no more, no less .. I will take a look @ that this evening. 
as a preview it may comes from recent modifications Andrew made on master, I saw some commits regarding static linking but i didn't pull that code. I will check

**Comment by sebastien-bouffier** [comment]
I changed the way libs are linked for lin and made a new dist (release is updated). Tell me if it works for you.

**Comment by davephillips** [comment]
Wow, that lightened the dependency load ! :) Thanks a lot, it appears that my issue is resolved. Impressive work !

**Comment by sebastien-bouffier** [comment]
you are welcome. Lin and Mac os x are statically linked, win ... I am still not able to do the same thing but it works ...

**Comment by sebastien-bouffier** [comment]
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.
